shop/core/urls.py
from django.urls import path, re_path
from core.views import index, help, show_category, show_item, show_cart, add_to_cart, remove_from_cart, update_cart_item, show_checkout, create_payment, create_order, success_view, cancel_view, coinbase_webhook

app_name = "core"

urlpatterns = [
    path('', index, name='home'),
    path('help/', help, name='help'),
    
    path('category/<slug:cat_slug>/', show_category, name='category'),
    path('item/<slug:item_slug>/', show_item, name='item'),

    path('cart/', show_cart, name="cart"),
    path('create-order/', create_order, name='create-order'),
    path('checkout/', show_checkout, name="checkout"),

    path('success/', success_view, name='payments-success'),
    path('cancel/', cancel_view, name='payments-cancel'),
]

shop/shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from shop import settings
from django.conf.urls.i18n import i18n_patterns

from core.views import pageNotFound, add_to_cart, remove_from_cart, update_cart_item, coinbase_webhook, create_payment, index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('i18n/', include('django.conf.urls.i18n')),
    path('add-to-cart', add_to_cart, name="add-to-cart"),
    path('remove-from-cart', remove_from_cart, name="remove-from-cart"),
    path('update-cart-item', update_cart_item, name="update-cart-item"),
    path('coinbase-webhook', coinbase_webhook, name='coinbase-webhook'),
    path('payment', create_payment, name="payment"),
]

urlpatterns += i18n_patterns(
    path("", include("core.urls")),
    path('user/', include('userauths.urls')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

handler404 = pageNotFound

shop/userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
    path("account/", views.my_account, name="account"),
]

shop/userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    email = models.EmailField(unique=True, null=False)
    username = models.CharField(max_length=100)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    def __str__(self) -> str:
        return self.email

shop/userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User
from django.utils.translation import gettext as _


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email'] 
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': _('Никнейм'),
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': _('Email'), 
            }),
            'password1': forms.PasswordInput(attrs={
                'class': 'form-control',
                'placeholder': _('Пароль'),
            }),
            'password2': forms.PasswordInput(attrs={
                'class': 'form-control',
                'placeholder': _('Подтвердите пароль'),
            }),
        }

shop/userauths/views.py
from django.shortcuts import render, redirect
from userauths.forms import UserRegisterForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from userauths.models import User
from core.models import Category
from email_utils.email_utils import send_registration_email
from email_utils.email_utils import send_password_change_mail
from django.utils.translation import gettext as _
from django.utils.translation import get_language


messages_locale = {
    'en': {
        'mail_exist': "A user with this email already exists.",
        'username_exist': "A user with this username already exists.",
        'password_mismatch': "Passwords do not match.",
        'account_created': "Your account has been successfully created, {username}.",
        'already_logged_in': "You are already logged in.",
        'user_does_not_exist': "This user does not exist, please register.",
        'user_email_does_not_exist': "User with email {email} does not exist.",
        'logged_out': "You have successfully logged out.",
        'password_changed': "Password successfully changed.",
        'incorrect_current_password': "Incorrect current password.",
        'logged_in' : 'Logged in!',
        "need_log_in": "Log in before action.",
        "register_title": "Sign up",
        "login_title": "Sign in",
        "my_acc_title": "My account",
    },
    'ru': {
        'mail_exist': "Пользователь с такой почтой уже существует.",
        'username_exist': "Пользователь с таким никнеймом уже существует.",
        'password_mismatch': "Пароли не совпадают.",
        'account_created': "Аккаунт успешно создан, {username}.",
        'already_logged_in': "Вы уже вошли в аккаунт.",
        'user_does_not_exist': "Данный пользователь не существует, зарегистрируйтесь.",
        'user_email_does_not_exist': "Пользователя с почтой {email} не существует.",
        'logged_out': "Вы успешно вышли из аккаунта.",
        'password_changed': "Пароль успешно изменен.",
        'incorrect_current_password': "Неправильно введен текущий пароль.",
        'logged_in' : 'Вы успешно вошли!',
        "need_log_in": "Необходимо войти в аккаунт.",
        "register_title": "Регистрация",
        "login_title": "Авторизация",
        "my_acc_title": "Личный кабинет",
    },
}

def get_message(msg_id):
    current_language = get_language()
    if current_language in messages_locale:
        if msg_id in messages_locale[current_language]:
            return messages_locale[current_language][msg_id]
    
    return "None"


# User = settings.AUTH_USER_MODEL
categories = Category.objects.all()

def register_view(request):
    if request.user.is_authenticated:
        messages.warning(request, get_message('already_logged_in'))
        return redirect("core:home")
    

    context = {
        "categories" : categories,
        "title": get_message("register_title")
    }

    if request.method == "POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")

        if password1 != password2:
            context["msz"] = get_message('password_mismatch')
            context["col"] = "alert-danger"
        else:
            if User.objects.filter(username=username).exists():
                context["msz"] = get_message('username_exist')
                context["col"] = "alert-danger"
            elif User.objects.filter(email=email).exists():
                context["msz"] = get_message('mail_exist')
                context["col"] = "alert-danger"
            else:
                user = User.objects.create_user(username=username, email=email, password=password1)
                messages.success(request, get_message('account_created').format(username=username))
                new_user = authenticate(username=email,
                                        password=password1
                                        )
                login(request, new_user)
                user = request.user
                send_registration_email(user=user)
                return redirect("core:home")

    return render(request, "userauths/sign-up.html", context)

def login_view(request):
    context = {
        "categories" : categories,
        "title": get_message("login_title")
    }

    if request.user.is_authenticated:
        messages.warning(request, get_message('already_logged_in'))
        return redirect("core:home")
    
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email = email, password = password)

            if user is not None:
                login(request, user)
                messages.success(request, get_message('logged_in'))
                return redirect("core:home")
            else:
                context["msz"] = get_message('user_does_not_exist')
                context["col"] = "alert-danger"
        except:
            context["msz"] = get_message('user_email_does_not_exist').format(email=email)
            context["col"] = "alert-danger"

    return render(request, "userauths/sign-in.html", context)

def logout_view(request):
    logout(request)
    messages.success(request, get_message('logged_out'))

    return redirect("userauths:sign-in")

def my_account(request):
    context = {
        "username" : request.user.username,
        "email" : request.user.email,
        "categories" : categories,
        "title": get_message("my_acc_title")
    }

    if request.user.is_authenticated:
        if request.method=="POST":
            current = request.POST["cpwd"]
            new_pas = request.POST["npwd"]

            user = User.objects.get(id=request.user.id)
            username = user.username

            check = user.check_password(current)

            if check==True:
                user.set_password(new_pas)
                user.save()
                context["msz"] = get_message('password_changed')
                user = User.objects.get(username=username)
                login(request,user)
                send_password_change_mail(user)
            else:
                context["msz"] = get_message('incorrect_current_password')
                context["col"] = "alert-danger"

            return render(request, "userauths/my-account.html", context)
        return render(request, "userauths/my-account.html", context)
    else:
        messages.warning(request, get_message('need_log_in'))
        return redirect("core:home")

shop/templates/userauths/my-account.html
{% extends 'core/base.html' %}
{% load static i18n %}

{% block css %}
<link rel="stylesheet" href="{% static 'assets/css/my-account.css' %}?v={{ random_number }}"> 
{% endblock %}

{% block content %}


<div class="section-account">
    <div class="container-account">

        <div class="account-card">
            <div class="account-header"> {% trans 'ВАШ АККАУНТ' %} </div>

            <div class="account-content">
                <img class="profile-img" src="{% static './assets/img/profile.png' %}" alt="">
            
                <div class="account-data-content">
                    <div class="account-data">
                        <div>{% trans 'Логин' %}: </div>
                        <div>{{ username }}</div>
                    </div>
                    <div class="account-data">
                        <div>{% trans 'Email' %}: </div>
                        <div>{{ email }}</div>
                    </div>

                    <div class="account-password">
                        {% trans 'Для смены пароля' %}:
                    </div>

                    <div class="passwd">
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="password" id="old_password" class="form-control" name="cpwd" placeholder="{% trans 'Старый пароль' %}" required>
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" name="npwd" id="pas" placeholder="{% trans 'Новый пароль' %}" required onkeyup="check_pass()">
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" id="cpas" placeholder="{% trans 'Подтверждение пароля' %}" required onkeyup="check_pass()">
                            </div>
                            <div>
                            {% if msz %}
                                <div class="alert {{col}}">{{msz}}</div>
                            {% endif %}
                            </div>
                            <button type="submit" class="sumbit-btn" id="change_password_button" value="Change Password" id="sbbtn">{% trans 'Подтвердить' %}</button>
                            
                        </form>
                    </div>
                </div>
            </div>
            
        </div>
        
    </div>
</div>



{% endblock %}

{% block script %}
<script>
    function check_pass(){
        let p = $("#pas").val();
        let cp = $("#cpas").val();
        
        if(p==cp){
            $("#pas").css("border","1px solid green");
            $("#cpas").css("border","1px solid green");
            $(".sumbit-btn").removeAttr("disabled");
        }else{
            $("#pas").css("border","1px solid red");
            $("#cpas").css("border","1px solid red");
            $(".sumbit-btn").attr("disabled","disabled");
        }
    }
</script>
{% endblock %}

shop/templates/userauths/sign-in.html
{% extends 'core/base.html' %}
{% load static i18n %}

{% block css %}
<link rel="stylesheet" href="{% static 'assets/css/sign-up.css' %}?v={{ random_number }}"> 
{% endblock %}

{% block content %}

<div class="section-sign-up">
    <div class="container-sign-up">
        <img class="register-img" src="{% static './assets/img/register/register.png' %}" alt="register-img">

        <div class="register-form">

            <div>
                <div class="registration-header">
                    {% trans 'ВХОД' %}
                </div>

                <div class="line"></div>

                <form action="" method="post">
                    {% csrf_token %}
                    
                    <div class="form-group">
                        <input type="text" required name="email" placeholder="{% trans 'Email' %}">    
                    </div>
                    <div class="form-group">
                        <input required type="password" name="password" placeholder="{% trans 'Ваш пароль *' %}">
                    </div>

                    <div>
                        {% if msz %}
                            <div class="alert {{col}}">{{msz}}</div>
                        {% endif %}
                    </div>
                    
                    <div class="btn-container">
                        <button class="submit-btn" type="submit"> {% trans 'Войти' %} </button>
                    </div>

                    <div class="have-acc-text">
                        {% trans 'Нет аккаунта?' %} <a href="{% url 'userauths:sign-up' %}"> {% trans 'Создайте!' %} </a> 
                    </div>
                </form>

                {% if form.errors %}
                <div class="alert alert-danger">
                    <ul>
                        {% for field, errors in form.errors.items %}
                            {% for error in errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
            </div>

            
        </div>
        
    </div>
</div>
{% endblock %}

{% block script %}

{% endblock %}

shop/templates/userauths/sign-up.html
{% extends 'core/base.html' %}
{% load static i18n %}

{% block css %}
<link rel="stylesheet" href="{% static 'assets/css/sign-up.css' %}?v={{ random_number }}"> 
{% endblock %}

{% block content %}

<div class="section-sign-up">
    <div class="container-sign-up">
        <img class="register-img" src="{% static './assets/img/register/register.png' %}" alt="register-img">

        <div class="register-form">

            <div>
                <div class="registration-header">
                    {% trans 'РЕГИСТРАЦИЯ' %}
                </div>

                <div class="line"></div>

                <form action="" method="post">
                    {% csrf_token %}
                    
                    <div class="form-group">
                        <input type="text" required name="username" placeholder="Username">    
                    </div>
                    <div class="form-group">
                        <input type="text" required name="email" placeholder="Email">    
                    </div>
                    <div class="form-group">
                        <input required type="password" id="password1" name="password1" placeholder="Password" required onkeyup="check_pass()">
                    </div>
                    <div class="form-group">
                        <input required type="password" id="password2" name="password2" placeholder="Confirmation" required onkeyup="check_pass()">
                    </div>
                    <div>
                        {% if msz %}
                            <div class="alert {{col}}">{{msz}}</div>
                        {% endif %}
                    </div>
                    <div class="btn-container">
                        <button class="submit-btn" type="submit"> {% trans 'Регистрация' %} </button>
                    </div>

                    <div class="have-acc-text">
                        {% trans 'Уже есть аккаунт?' %} <a href="{% url 'userauths:sign-in' %}"> {% trans 'Войдите' %} </a> 
                    </div>
                </form>
            </div>

            
        </div>
        
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    function check_pass(){
        let p = $("#password1").val();
        let cp = $("#password2").val();
        
        if(p==cp){
            $("#password1").css("border","2px solid green");
            $("#password2").css("border","2px solid green");
            $(".submit-btn").removeAttr("disabled");
        }else{
            $("#password1").css("border","1px solid red");
            $("#password2").css("border","1px solid red");
            $(".submit-btn").attr("disabled","disabled");
        }
    }
</script>
{% endblock %}