shop/core/urls.py
from django.urls import path, re_path
from core.views import index, help, show_category, show_item, show_cart, add_to_cart, remove_from_cart, update_cart_item, show_checkout, create_payment, create_order, success_view, cancel_view, coinbase_webhook

app_name = "core"

urlpatterns = [
    path('', index, name='home'),
    path('help/', help, name='help'),
    
    path('category/<slug:cat_slug>/', show_category, name='category'),
    path('item/<slug:item_slug>/', show_item, name='item'),

    path('cart/', show_cart, name="cart"),
    path('create-order/', create_order, name='create-order'),
    path('checkout/', show_checkout, name="checkout"),

    path('success/', success_view, name='payments-success'),
    path('cancel/', cancel_view, name='payments-cancel'),
]

shop/shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from shop import settings
from django.conf.urls.i18n import i18n_patterns

from core.views import pageNotFound, add_to_cart, remove_from_cart, update_cart_item, coinbase_webhook, create_payment, index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('i18n/', include('django.conf.urls.i18n')),
    path('add-to-cart', add_to_cart, name="add-to-cart"),
    path('remove-from-cart', remove_from_cart, name="remove-from-cart"),
    path('update-cart-item', update_cart_item, name="update-cart-item"),
    path('coinbase-webhook', coinbase_webhook, name='coinbase-webhook'),
    path('payment', create_payment, name="payment"),
]

urlpatterns += i18n_patterns(
    path("", include("core.urls")),
    path('user/', include('userauths.urls')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

handler404 = pageNotFound

shop/userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
    path("account/", views.my_account, name="account"),
]

shop/core/models.py
from pyexpat import model
from django import forms
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from userauths.models import User
from django.utils.html import mark_safe
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator 

STATUS_CHOICE = {
    ("process", "Processing"),
}

STATUS = {
    ("draft", "Draft"),
    ("disabled", "Disabled"),
    ("published", "Published"),
}

def user_directiory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class Category(models.Model):
    cid = ShortUUIDField(unique=True, length=10, max_length=30, prefix="cat", alphabet="abcdefgh12345")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")

    title = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Categories"
    
    def __str__(self) -> str:
        return self.title

class Country(models.Model):
    coid = ShortUUIDField(unique=True, length=10, max_length=30, alphabet="abcdefgh12345")
    title = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Countries"

    def __str__(self) -> str:
        return self.title
    
class Product(models.Model):
    pid = ShortUUIDField(unique=True, length=10, max_length=30, alphabet="abcdefgh12345")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)

    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to=user_directiory_path, null=False, default="product.png")
    description = models.TextField(null=False, blank=False, default="Товар в нашем магазине")
    accessories = models.TextField(blank=True, null=True, default="Поле может быть пустым. Иначе введите список комплектации с помощью переноса строки.")

    countries = models.ManyToManyField(Country, related_name='products')

    price = models.DecimalField(max_digits=9, decimal_places=2, default=9.99)

    product_status = models.CharField(choices=STATUS,  max_length=10, default="draft")

    status = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    
    sku = ShortUUIDField(unique=True, length=4, max_length=10, prefix= "sku", alphabet="1234567890")

    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Products"

    def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
    
    def get_accessories_list(self):
        if self.accessories:
            return self.accessories.split('\n')
        else:
            return []

    def __str__(self) -> str:
        return self.title


# Cart, Order, OrderItem

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def total_items(self):
        return self.cartitem_set.count()

    def total_price(self):
        return sum(item.total_price() for item in self.cartitem_set.all())

    def __str__(self):
        return f"Cart for {self.user.username}"
    
    class Meta:
        verbose_name_plural = "Carts"

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, default="1")
    image = models.ImageField(upload_to=user_directiory_path, null=False, default="product.png")    
    quantity = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    price = models.DecimalField(max_digits=10, decimal_places=2) 

    def clean(self):
        super().clean()
        if self.quantity < 1:  
            self.quantity = 1  

    def cart_item_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def total_price(self):
        return self.quantity * self.price

    def __str__(self):
        return f"{self.product.title} ({self.quantity} units)"
    
    class Meta:
        verbose_name_plural = "Cart items"

class Order(models.Model):
    oid = ShortUUIDField(unique=True, length=10, max_length=30, prefix="order", alphabet="ABCDEFG12345")
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    PAYMENT_STATUS_CHOICES = [
        ('pending', 'Ожидание оплаты'),
        ('paid', 'Оплачено'),
        ('failed', 'Ошибка оплаты'),
        ('refunded', 'Возврат средств'),
    ]

    payment_status = models.CharField(
        max_length=10,
        choices=PAYMENT_STATUS_CHOICES,
        default='pending',
    )

    def __str__(self):
        return f"Order #{self.pk} - {self.get_payment_status_display()}"
    
    class Meta:
        verbose_name_plural = "Orders"

# Payment methods: crypto
class Payment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    description = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Payment #{self.id}'
    
    class Meta:
        verbose_name_plural = "Payments"

shop/core/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.conf import settings
from coinbase_commerce.client import Client
from core.tasks import delete_payment
from coinbase_commerce.error import SignatureVerificationError, WebhookInvalidPayload
from coinbase_commerce.webhook import Webhook
from django.views.decorators.csrf import csrf_exempt, ensure_csrf_cookie
from django.views.decorators.http import require_http_methods
from django.urls import reverse
from django.utils.translation import gettext as _
from django.utils.translation import get_language

from core.models import Product, Category, Cart, CartItem, Payment, Order

from email_utils.email_utils import send_order_confirmation_email, send_create_order_mail, send_cancel_order_mail

import os
from dotenv import load_dotenv

load_dotenv()

num_of_products = int(os.getenv("NUMBER_OF_PRODUCTS_ON_MAIN_PAGE"))

def exit_if_not_logged_in(request):
    if not request.user.is_authenticated:
        messages.warning(request, _("Вам необходимо войти в аккаунт."))
        return True
    return False

from django.utils.translation import get_language


messages_locale = {
    'en': {
        "help_title": "Support",
        "cart_title": "Cart",
        "checkout_title": "Order",
        "success_title": "Success",
        "cancel_title": "Cancel",
        "order_on_site" : "Payment on site ",
        "order": "Order ",
    },
    'ru': {
        "help_title": "Поддержка",
        "cart_title": "Корзина",
        "checkout_title": "Оформление заказа",
        "success_title": "Успешно",
        "cancel_title": "Отмена",
        "order_on_site" : "Оплата заказа на сайте ",
        "order": "Заказ ",
    },
}

def get_message(msg_id):
    current_language = get_language()
    if current_language in messages_locale:
        if msg_id in messages_locale[current_language]:
            return messages_locale[current_language][msg_id]
    
    return "None"


categories = Category.objects.all()

def index(request):
    products = Product.objects.filter(product_status="published")

    content = {
        'title': os.getenv("SITE_NAME"),
        "categories" : categories,
        "products" : products,
    }

    filtered_products = {}
    for category in categories:
        category_products = products.filter(category=category, product_status="published")[:num_of_products]  
        filtered_products[category] = category_products

    content['filtered_products'] = filtered_products

    return render(request, 'core/index.html', content)

def help(request):
    content = {
        'title': get_message("help_title"),
        "categories" : categories,
    }
    return render(request, 'core/help.html', content)

def show_category(request, cat_slug): 
    category = get_object_or_404(Category, slug=cat_slug)
    products = Product.objects.filter(category=category)

    content = {
        'title': category.title,
        "categories": categories,
        "category" : category,  
        "products" : products,
    }
    return render(request, 'core/showcase.html', content)

def show_item(request, item_slug):
    is_authenticated = request.user.is_authenticated
    item = get_object_or_404(Product, slug=item_slug)
    products = Product.objects.filter(category=item.category, product_status="published")

    content = {
        'title': item.title,
        'item': item,
        'products': products,
        "categories" : categories,
        'is_authenticated': is_authenticated,
    }
    return render(request, 'core/item.html', content)

@require_POST
def add_to_cart(request):
    if exit_if_not_logged_in(request):
        return redirect("core:home")
    
    try:
        if request.method == 'POST':
            product_id = request.POST.get('id')
            product_country_id = request.POST.get('country')
            quantity = int(request.POST.get('qty'))
            product_price = float(request.POST.get('price'))

            product = Product.objects.get(pk=product_id)
            product_image = product.image

            user = request.user

            cart_tuple = Cart.objects.get_or_create(user=user)
            cart = cart_tuple[0]

            cart_item, item_created = CartItem.objects.get_or_create(
                cart=cart,
                product_id=product_id,
                country_id=product_country_id,
                defaults={
                    'image': product_image,
                    'quantity': quantity,
                    'price': product_price
                }
            )

            if not item_created:
                cart_item.quantity += quantity
                cart_item.save()

            return JsonResponse({'message': 'Product added to cart', 'cart_total': cart.total_items})
    except Exception as e:
        print(e)
        return JsonResponse({'error': str(e)})
    
    return JsonResponse({'error': 'Invalid request method'})

@require_POST
def remove_from_cart(request):
    if exit_if_not_logged_in(request):
        return redirect("core:home")
    try:
        if request.method == 'POST':
            product_id = request.POST.get('id')
            user = request.user

            cart_tuple = Cart.objects.get_or_create(user=user)
            cart = cart_tuple[0]

            cart_item = CartItem.objects.get(cart=cart.id, id=product_id)
            cart_item.delete()

            cart_items = CartItem.objects.filter(cart = cart.id)

            if cart_items.exists:
                new_cart_total_price = cart.total_price()
                return JsonResponse({'message': 'Product removed from cart', 'cart_total_price': new_cart_total_price})
            else:
                return JsonResponse({'message': 'Product removed from cart', 'cart_is_empty': True})
            
    except Exception as e:
        print(e)
        return JsonResponse({'error': str(e)})
    
    return JsonResponse({'error': 'Invalid request method'})

def show_cart(request):
    if exit_if_not_logged_in(request):
        return redirect("core:home")
    
    is_authenticated = request.user.is_authenticated
    
    cart_tuple = Cart.objects.get_or_create(user=request.user)
    cart = cart_tuple[0]

    cart_items = CartItem.objects.filter(cart = cart)
    cart_items_exist = cart_items.exists

    content = {
        'title': get_message("cart_title"),
        'categories': categories,
        'cart_items': cart_items,
        'cart': cart,
        'is_authenticated': is_authenticated,
        'cart_items_exist': cart_items_exist,
    }
    return render(request, 'core/cart.html', content)

def update_cart_item(request):
    if exit_if_not_logged_in(request):
        return redirect("core:home")
    
    if request.method == 'POST':
        cart_item_id = request.POST.get('cart_item_id')
        quantity = request.POST.get('quantity')

        cart = Cart.objects.get_or_create(user=request.user)
        
        cart_item = get_object_or_404(CartItem, id=cart_item_id, cart=cart[0])
        
        cart_item.quantity = int(quantity)
        cart_item.save()
        
        item_cart_total_price = cart_item.total_price()
        new_cart_total_price = cart[0].total_price()

        return JsonResponse({'success': True, 'item_cart_total_price': item_cart_total_price, 'cart_total_price': new_cart_total_price})
    else:
        return JsonResponse({'success': False})
    
def create_order(request):
    if exit_if_not_logged_in(request):
        return redirect("core:home")

    if request.method == 'POST':
        user = request.user

        cart, created = Cart.objects.get_or_create(user=user)

        order = Order.objects.get_or_create(cart=cart, payment_status = 'pending')
        
        order[0].total = cart.total_price()
        order[0].save()      

        return redirect('core:checkout')

    return redirect('core:cart')

def show_checkout(request):
    if exit_if_not_logged_in(request):
        return redirect("core:home")
    
    cart_tuple = Cart.objects.get_or_create(user=request.user)
    cart = cart_tuple[0]

    cart_items = CartItem.objects.filter(cart = cart)
    cart_items_exist = cart_items.exists

    content = {
        'title': get_message("checkout_title"),
        'categories': categories,
        'user': request.user,
        'cart_items': cart_items,
        'cart_items_exist': cart_items_exist,
        'is_authenticated': request.user.is_authenticated,
        'cart': cart,
    }
    return render(request, 'core/checkout.html', content)

def success_view(request):
    if exit_if_not_logged_in(request):
        return redirect("core:home")
    content = {
        'title': get_message("success_title"),
        'categories': categories,
    }
    return render(request, 'core/success.html', content)


def cancel_view(request):
    if exit_if_not_logged_in(request):
        return redirect("core:home")
    content = {
        'title': get_message("cancel_title"),
        'categories': categories,
    }
    return render(request, 'core/cancel.html', content)


def create_payment(request):
    if exit_if_not_logged_in(request):
        return redirect("core:home")
    
    if request.method == 'POST':
        api_key = settings.COINBASE_API_KEY

        user = request.user
        cart = get_object_or_404(Cart, user=user)
        order_tuple = Order.objects.get_or_create(Order, cart=cart, payment_status='pending')
        order = order_tuple[0]

        total = cart.total_price()

        payment = Payment.objects.get_or_create(order=order, description=user.email)

        order_string = get_message("order")

        client = Client(api_key)
        charge_data = {
            "name": order_string + "#" + str(order.oid).replace("order", ""), 
            "description": get_message("order_on_site") + os.getenv("SITE_NAME"),
            "local_price": {

shop/templates/core/base.html
{% load static i18n %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{{title}}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{% static 'assets/img/fav.ico' %}" type="image/x-icon">

        <meta property="og:title" content="">
        <meta property="og:type" content="">
        <meta property="og:url" content="">
        <meta property="og:image" content="">
            
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'assets/css/normalize.css' %}"> 
        <link rel="stylesheet" href="{% static 'assets/css/base.css' %}?v={{ random_number }}"> 

        {% block css %}
        {% endblock %}

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
      
        <meta name="theme-color" content="#fafafa">
      </head>

<body>

<!-- Header -->

<header>
  <div class="mobile-navbar">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a href="{% url 'core:home' %}">
          <img class="header-logo" src="{% static './assets/img/logo.svg' %}" alt="logo-image">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <div class="burger-btn">
            <span class="navbar-toggler-icon">☰</span>
          </div>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">

            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'userauths:account' %}"> 
                {% trans 'Мой аккаунт' %} 
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:cart' %}"> 
                {% trans 'Корзина' %} 
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'userauths:sign-out' %}"> 
                {% trans 'Выход' %} 
              </a>
            </li>
            {% else %}
            {% endif %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:help' %}">
                {% trans 'Поддержка' %}
              </a>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="languageDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {% trans 'Язык' %}
              </a>
              <ul class="dropdown-menu" aria-labelledby="languageDropdown">
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                <li>
                  <a class="dropdown-item language-option" href="#" data-value="{{ language.code }}">{{ language.name_local }}</a>
                </li>
                {% endfor %}
              </ul>
              <form action="{% url 'set_language' %}" method="post" class="language-form">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ redirect_to }}">
                <input type="hidden" name="language" id="selected-language" value="{{ LANGUAGE_CODE }}">
              </form>
            </li>
            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {% trans 'Категории' %}
              </a>
              <ul class="dropdown-menu">
                {% for category in categories %}
                <li> 
                  <a class="dropdown-item" href="{% url 'core:category' cat_slug=category.slug %}">
                   {{category.title}}
                  </a>
                </li>
                {% endfor %}
              </ul>
            </li>

            {% if request.user.is_authenticated %}
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'userauths:sign-in' %}"> {% trans 'Вход' %} </a>
            </li>
           {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </div>

  <script>
    document.addEventListener("DOMContentLoaded", function() {
      const languageOptions = document.querySelectorAll(".language-option");
      const selectedLanguage = document.querySelector("#selected-language");
  
      languageOptions.forEach(function(option) {
        option.addEventListener("click", function(e) {
          e.preventDefault();
          const selectedValue = option.getAttribute("data-value");
          selectedLanguage.value = selectedValue;
          document.querySelector(".language-form").submit();
        });
      });
    });
  </script>

  <div class="header-section">
    <div class="header-container">

      <div class="dropdown-language">
        
        <div class="custom-select">
          <span class="selected-option">{% trans 'Язык' %}</span>
          <ul class="options">
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
            <li>
              <a href="#" data-value="{{ language.code }}">{{ language.name_local }}</a>
            </li>
            {% endfor %}
          </ul>
          <form action="{% url 'set_language' %}" method="post" class="language-form">
            {% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}">
            <input type="hidden" name="language" id="selected-language" value="{{ LANGUAGE_CODE }}">
          </form>
        </div>
        
      </div>

      <script>
        document.addEventListener("DOMContentLoaded", function() {
            const customSelect = document.querySelector(".custom-select");
            const selectedOption = customSelect.querySelector(".selected-option");
            const optionsList = customSelect.querySelector(".options");
            const languageForm = customSelect.querySelector(".language-form");
            const selectedLanguage = customSelect.querySelector("#selected-language");          

            selectedOption.addEventListener("click", function() {
              customSelect.classList.toggle("active");
            });         

            optionsList.addEventListener("click", function(e) {
              if (e.target.tagName === "A") {
                const selectedValue = e.target.getAttribute("data-value");
                selectedOption.textContent = e.target.textContent;
                selectedLanguage.value = selectedValue;
                languageForm.submit();
              }
            });
          });
        </script>

      
      <a href="{% url 'core:home' %}">
        <img class="header-logo" src="{% static './assets/img/logo.svg' %}" alt="logo-image">
      </a>

      <div class="right-content-of-header">
      <div class="categories-dropdown">
        <ul class="custom-ul">
          <li>
              <a href="#"> {% trans 'Категории' %} </a>
            <ul class="dropdown">
              {% for category in categories %}
              <li> 
                <a href="{% url 'core:category' cat_slug=category.slug %}">
                  <div class="header-text">
                    {{category.title}}
                  </div>
                </a>
              </li>
              {% endfor %}
            </ul>
          </li>
        </ul>
      </div>

      

      <a href="{% url 'core:help' %}">
        <div class="header-text">
          {% trans 'Поддержка' %}
        </div>
      </a>
    </div>

      <div class="dropdown-account">
        <ul class="custom-ul">
          <li>
              {% if request.user.is_authenticated %}
              <a href="#"> {% trans 'Аккаунт' %} </a>
            <ul class="dropdown">
              <li> <a href="{% url 'userauths:account' %}"> {{ request.user.username|slice:":7" }} </a> </li>
              <li> <a href="{% url 'userauths:account' %}"> {% trans 'Мой аккаунт' %} </a> </li>
              <li> <a href="{% url 'core:cart' %}"> {% trans 'Корзина' %} </a> </li>
              <li> <a href="{% url 'userauths:sign-out' %}"> {% trans 'Выход' %} </a> </li>
            </ul>
              {% else %}
              <li> <a href="{% url 'userauths:sign-in' %}"> {% trans 'Вход' %} </a> </li>
              {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </div>

</header>

<!-- Блок контента -->
<div class="content-text">

{% block content %}
{% endblock %}

	</div>

  <div class="innerdiv">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}">
      <strong> {{ message }} </strong>
    </div>
    {% endfor %}
  {% endif %}
<script>
  setTimeout (() => {
    $(".alert").alert("close")
  }, 3000)
</script> 
</div>


<!-- Footer -->
<footer>
  <div class="footer-container">
    2023 @companyName
  </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
<script src="{% static './assets/js/main.js' %}?<?=$cur_time;?>"></script>

{% block script %}
{% endblock %}

</body>
</html>

shop/templates/core/index.html
{% extends 'core/base.html' %}
{% load static i18n %}

{% block css %}
<link rel="stylesheet" href="{% static 'assets/css/index.css' %}?v={{ random_number }}"> 
{% endblock %}

{% block content %}

<div class="section-1">
  <div class="container-1">
    <div class="crypto-text-top">
      {% trans 'Любой текст, который вы захотите сюда добавить' %}
    </div>
    <img class="crypto-image" src="{% static './assets/img/core-img/crypto-2.png' %}" alt="crypto-image">
  </div>
</div>
<div class="decoration-element"></div>
<div class="section-2">
  <div class="container-2">
    <div class="block-content-review">
      <img class="content-review-img" src="{% static './assets/img/core-img/reputation.png' %}" alt="reputation-img">
      <div class="header-review-text">
        {% trans 'Репутация' %}
      </div>
      <div class="text-review-content">
        {% trans 'Наш магазин работает уже несколько лет и имеет хорошую репутацию' %}
      </div>
    </div>
    <div class="block-content-review">
      <img class="content-review-img" src="{% static './assets/img/core-img/trust.png' %}" alt="trust-img">
      <div class="header-review-text">
        {% trans 'Гарантия' %}
      </div>
      <div class="text-review-content">
        {% trans 'Мы предоставляем гарантию на все продаваемые товары' %}
      </div>
    </div>
    <div class="block-content-review">
      <img class="content-review-img" src="{% static './assets/img/core-img/professional.png' %}" alt="professional-img">
      <div class="header-review-text">
        {% trans 'Профессионализм' %}
      </div>
      <div class="text-review-content">
        {% trans 'Наша команда профессионалов всегда готова помочь и ответить на все вопросы' %}
      </div>
    </div>
  </div>
</div>
<div class="section-3">
  <div class="container-3">

    {% for category, category_products in filtered_products.items %}
      <div class="column">
          <div class="column-header">
              <div class="line-near-text"></div>
              {{ category.title }}
              <div class="line-near-text"></div>
          </div>
      
          {% for product in category_products %}
          <div class="shop-item">
              <img class="item-picture" width="100" height="100" src="{{ product.image.url }}" alt="">
              <div>
                  <div class="item-header">
                    <a style="all: unset;" href="{% url 'core:item' item_slug=product.slug %}">{{ product.title }}</a>
                  </div>
                  <div class="item-price">
                      ${{ product.price }}
                  </div>
              </div>
          </div>
          {% endfor %}
      
          <a href="{% url 'core:category' cat_slug=category.slug %}" class="view-all-btn"> {% trans 'Смотреть все' %} </a>
      </div>
      {% endfor %}

    
  </div>
</div>

{% endblock %}

shop/templates/core/showcase.html
{% extends 'core/base.html' %}
{% load static i18n %}

{% block css %}
<link rel="stylesheet" href="{% static 'assets/css/showcase.css' %}"> 
<link rel="stylesheet" href="{% static 'assets/css/item-card.css' %}"> 
{% endblock %}

{% block content %}

<div class="section-items">
    <div class="container-items">
      <div class="category-header">
        {{category.title}}
      </div>
      <div class="show-case">

        {% for product in products %}

        {% if product.product_status == 'published' %}
        <div class="item-card">
          <div class="show-case-item">
            <img class="show-case-img" src="{{ product.image.url }}" alt="">
            <div class="show-case-category">
                {{category.title}}
            </div>
            <div class="show-case-item-name">
              <a style="all: unset;" href="{% url 'core:item' item_slug=product.slug %}"> {{product.title}} </a>
            </div>
            <div class="item-price">
              {{product.price}}
            </div>
          </div>
        </div>
        {% endif %}

        {% endfor %}

      </div>
    </div>
  </div>
  
{% endblock %}